import type { FileNode } from './types'
// @ts-ignore - Virtual module generated by vite-plugin-docs-filesystem
import docsFileSystem from 'virtual:docs-filesystem'

// 规范化路径
function normalizePath(path: string): string {
  // 移除多余的斜杠
  let normalized = path.replace(/\/+/g, '/')
  // 移除末尾斜杠（除非是根目录）
  if (normalized.length > 1 && normalized.endsWith('/')) {
    normalized = normalized.slice(0, -1)
  }
  return normalized || '/'
}

// 解析路径（处理 . 和 ..）
function resolvePath(currentPath: string, targetPath: string): string {
  // 绝对路径
  if (targetPath.startsWith('/')) {
    return normalizePath(targetPath)
  }

  // 相对路径
  const parts = currentPath === '/' ? [] : currentPath.split('/').filter(Boolean)
  const targetParts = targetPath.split('/').filter(Boolean)

  for (const part of targetParts) {
    if (part === '..') {
      parts.pop()
    } else if (part !== '.') {
      parts.push(part)
    }
  }

  return '/' + parts.join('/')
}

// 根据路径查找节点
function findNode(root: FileNode, path: string): FileNode | null {
  const normalizedPath = normalizePath(path)

  if (normalizedPath === '/') {
    return root
  }

  const parts = normalizedPath.split('/').filter(Boolean)
  let current: FileNode | undefined = root

  for (const part of parts) {
    if (!current || current.type !== 'directory' || !current.children) {
      return null
    }
    current = current.children.find((child) => child.name === part)
  }

  return current || null
}

// 列出目录内容
function listDirectory(root: FileNode, path: string): FileNode[] | null {
  const node = findNode(root, path)
  if (!node || node.type !== 'directory') {
    return null
  }
  return node.children || []
}

// 虚拟文件系统 Composable
export function useVirtualFileSystem() {
  const fileSystem = docsFileSystem as FileNode

  return {
    fileSystem,
    normalizePath,
    resolvePath,
    findNode: (path: string) => findNode(fileSystem, path),
    listDirectory: (path: string) => listDirectory(fileSystem, path),
    isDirectory: (path: string) => {
      const node = findNode(fileSystem, path)
      return node?.type === 'directory'
    },
    isFile: (path: string) => {
      const node = findNode(fileSystem, path)
      return node?.type === 'file'
    },
    getFileRoute: (path: string) => {
      // 将虚拟路径转换为实际的博客路由
      // 例如: /frontend/react/react-router.md -> /frontend/react/react-router
      return path.replace(/\.md$/, '')
    }
  }
}
